### ISSUE TITLE
Set the size of the Led Circle

### ISSUE THREAD

**Issue by mschuricht** [Adorkable/node-red-contrib-ui-led#57] opened 2020-11-16 08:51 UTC
The size of the LED is too powerful compared to the label. An adjustment of the size would be desirable.
![image](https://user-images.githubusercontent.com/74533447/99231673-3a152d00-27f1-11eb-827c-16d63d5eaf40.png)

**Comment by yoiang** [comment] 2020-11-17 18:13
Forms of this request are happening more and more often, it will likely come in the next version!

**Comment by yoiang** [comment] 2021-01-13 07:13
Realized this is a duplicate of #17, closing to consolidate

**Closed by yoiang** 2021-01-13 07:13 UTC
Labels: enhancement
