### ISSUE TITLE
got "TypeError: Cannot read property 'length' of undefined"

### ISSUE THREAD

**Issue by gdallaire** [Adorkable/node-red-contrib-ui-led#44] opened 2019-09-24 03:09 UTC
**Describe the bug**
node red version  = 0.20.8

**To Reproduce**
1. install led-ui from "Manage palette"
2. add the led to a flow, set the label

**Expected behavior**
after deploying I get this error "TypeError: Cannot read property 'length' of undefined" and no led appears on the dashboard.

**Comment by yoiang** [comment] 2019-09-25 01:34
Hey @gdallaire , thanks so much for reporting the bug! 

I was able to reproduce it, I'll next set about what the issue is and see about a fix.

**Comment by yoiang** [comment] 2019-09-25 01:51
Oh right, so check it! When I was reproducing it this is what was happening, less a bug with **ui-led** and more a not uncommon UX issue with **node-red-dashboard**:

Notice how when you place the new node it has a red triangle:
<img width="161" alt="Screen Shot 2019-09-24 at 9 44 56 PM" src="https://user-images.githubusercontent.com/89718/65562552-d527b500-df14-11e9-9826-a9a162ffc824.png">

It's complaining because it can't find a default group to assign itself to. If you go into the node's configuration:
<img width="508" alt="Screen Shot 2019-09-24 at 9 45 27 PM" src="https://user-images.githubusercontent.com/89718/65562624-086a4400-df15-11e9-8599-9de3f82ac213.png">

Set this and you should be good!

Lemme know if this isn't the issue!

**Comment by gdallaire** [comment] 2019-09-25 11:54
when adding a ui-led there is a red triangle, I had to re-set the default group (that was already set) and then the red triangle was removed.

but ui-led still doesn't appear in the dashboard :(

![image](https://user-images.githubusercontent.com/3247909/65598426-5f016d80-df69-11e9-8097-0d3a04ca3f54.png)

**Comment by yoiang** [comment] 2019-09-25 12:30
Hmm, sorry to ask what may be silly questions, have you assigned it to a tab as well? Are there any additional complaints in the console?

**Comment by gdallaire** [comment] 2019-09-25 12:49
yes in the "Home" tab :+1: 


![image](https://user-images.githubusercontent.com/3247909/65602076-4432f700-df71-11e9-879e-c5879f1ff879.png)

Dashboard :

![image](https://user-images.githubusercontent.com/3247909/65602110-51e87c80-df71-11e9-9841-15a0d990be77.png)

**Comment by gdallaire** [comment] 2019-09-25 12:58
just took the time to upgrade to 0.3.1, restarted node-red, then the module was not installed anymore

![image](https://user-images.githubusercontent.com/3247909/65602767-7133d980-df72-11e9-8a40-9454e284a0a1.png)

then I re-installed it and now

![image](https://user-images.githubusercontent.com/3247909/65602877-9e808780-df72-11e9-94b4-3faec86b0531.png)

all seems OK !

thanks

**Closed** 2019-09-25 13:02 UTC

**Comment by yoiang** [comment] 2019-09-25 14:01
Perfect! I'm glad we could sort it out :)

**Comment by gaur-gaur** [comment] 2021-04-01 07:53
i am getting same issue  "TypeError: Cannot read property 'length' of undefined" in command promt in which i start node red command
